### PR TITLE
HPC-8351: Upgrade Node.js from v12 to v16

### PR DESCRIPTION
**Pull request by Pl217**
Since this repo uses `yarn`, it is independent from `npm v8` lockfile changes.

Updating `@unocha/hpc-repo-tools` to `v1.0.0` required to also update `eslint` and `typescript` packages, but I've also sneaked in updates to `lint-staged` and `prettier`, because I didn't want to open new PR just for that.

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by czmj — APPROVED** [review]

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Pull request merged**
