### PR TITLE
HPC-8383: Upgrade knex to latest version

### PR DESCRIPTION
**Pull request by Pl217**
Needs https://github.com/UN-OCHA/hpc-api-core/pull/154 to be merged first.

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by enxtur — APPROVED** [review]

**Pull request merged**
