### PR TITLE
Deploy `v4.3.0` to stage for testing

### PR DESCRIPTION
**Pull request by Pl217**
This PR is meant to be used to build Docker image for release of `v4.3.0`, with all code merged to `develop` since last release plus #94, which needs to be tested. Once Docker image is built, it will be deployed manually via Jenkins job, this PR is not meant for the actual stage release.

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-api:v4.3.0-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Comment by Pl217** [comment]
Version should have been `v4.3.0-test-1` (not just `v4.3.0`), like we did in https://github.com/UN-OCHA/hpc_service/pull/2799, but it's late now. There should be no name conflicts when we're indeed ready to deploy `v4.3.0`, but naming should have indicated that this is outstanding stage release, meant for testing.

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-api:v4.3.0-test-1-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Comment by Pl217** [comment]
Testing HPC-8026 is now completed successfully.

**Pull request closed without merging**
