### PR TITLE
Update documentation and dependencies

### PR DESCRIPTION
**Pull request by Pl217**
Minor (mostly stylistic) updates to documentation and also updating the npm packages.

### CODE REVIEW

**Review by s0 — APPROVED** [review]
LGTM, but needs prettier to be run

**Comment by Pl217** [comment]
> LGTM, but needs prettier to be run

The reason is updating `prettier` to `v2.3.0`, which brought some changes. I wonder how codebases are impacted by such changes. Keeping packages up-to-date seems like a logical thing to do, but should you reformat your codebase when a major change happens. This change affected just one file here, but in `app/` directory of `hpc_service`, there are 94 files that need change! I didn't know that when I proposed updating dependencies in https://github.com/UN-OCHA/hpc_service/pull/2233.

What is your opinion on how our codebase should response to changes like this? Should we stop updating, should we revert in `hpc_service` or should we keep our codebase at the bleeding edge? Or something else? :)

**Comment by s0** [comment]
We definitely want to keep them up to date, but we will also face this issue whenever we change configuration options in prettier without reformatting *everything*, so it is something we should be able to handle.

For the most part, the workflow should probably be that we make sure that formatting changes are done in separate commits, but we don't want to have to have massive formatting PRs all the time as that leads to too many conflicts.

**Comment by Pl217** [comment]
> We definitely want to keep them up to date, but we will also face this issue whenever we change configuration options in prettier without reformatting _everything_, so it is something we should be able to handle.
> 
> For the most part, the workflow should probably be that we make sure that formatting changes are done in separate commits, but we don't want to have to have massive formatting PRs all the time as that leads to too many conflicts.

As things stand now, changes in prettier are more likely to occur than changes in our configuration. I wasn't following their work over the years, so I don't know how often this happens, but from their [release notes](https://prettier.io/blog/2021/05/09/2.3.0.html) it looks like `v2.3.0` resolved some long standing problems. I would prefer that they changed major version every time they release versions which "break" previous behavior and cause such formatting changes. This is more a question directed towards prettier maintainers, but I'm sure they already discussed this :smile:

As for us, I think it's much more convenient that we apply changes in a single PR, which should not even need much of a review in my opinion, since CI checks for prettier formatting and making changes using prettier CLI tool with a `--write` flag should do the trick. It's much more convenient to reformat codebase in a single PR, and then rebase all other PRs to include the changes which they would be doing anyway (in a separate commit). We had one incident months ago, which was caused by a mistake during rebase, but I wouldn't necessarily blame formatting changes for that.

Edit: Changes in prettier can happen even in patch version updates. From their [docs page](https://prettier.io/docs/en/install.html#summary):
>Install an exact version of Prettier locally in your project. This makes sure that everyone in the project gets the exact same version of Prettier. Even a patch release of Prettier can result in slightly different formatting, so you wouldn’t want different team members using different versions and formatting each other’s changes back and forth.

**Pull request merged**
