### PR TITLE
:package: Prepare release `v4.2.0` and deploy to stage

### PR DESCRIPTION
**Pull request by czmj**

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-api:v4.2.0-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Review by Pl217 — CHANGES_REQUESTED** [review]
Why are there so many changes to `yarn.lock` in the commit where you do version bump - 6060c389054918d30e5bb647e3ac730822930ad4?

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-api:v4.2.0-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Comment by czmj** [comment]
> Why are there so many changes to `yarn.lock` in the commit where you do version bump - [6060c38](https://github.com/UN-OCHA/hpc-api/commit/6060c389054918d30e5bb647e3ac730822930ad4)?

I was having some trouble running yarn on my new laptop - I've sorted it out now. Thanks for the heads up.

**Review by Pl217 — APPROVED** [review]

**Pull request merged**
