### PR TITLE
Set ES2021 as Typescript compilation target

### PR DESCRIPTION
**Pull request by Pl217**

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by krishnareddy-tadi — APPROVED** [review]

**Pull request merged**
